function Farm(v,player)
    if v+0 == 1 then
        minetest.set_node({x=350, y=39, z=3}, {name="default:water_source"})
		minetest.set_node({x=351, y=39, z=3}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=3}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=350, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=350, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=40, z=3}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=3}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=351, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=351, y=40, z=2}, {name="farming:cotton_8"})
        minetest.set_node({x=345, y=40, z=-2}, {name="default:chest"})
		screwdriver_handler(player, {type="node", under={x=345, y=40, z=-2}, above={x=345, y=40, z=-2}}, 1)
	elseif v+0 == 2 then
		minetest.set_node({x=347, y=39, z=3}, {name="default:water_source"})
		minetest.set_node({x=348, y=39, z=3}, {name="farming:soil_wet"})
		minetest.set_node({x=346, y=39, z=3}, {name="farming:soil_wet"})
		minetest.set_node({x=346, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=347, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=348, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=346, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=347, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=348, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=348, y=40, z=3}, {name="farming:cotton_8"})
		minetest.set_node({x=346, y=40, z=3}, {name="farming:cotton_8"})
		minetest.set_node({x=346, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=347, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=348, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=346, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=347, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=348, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=353, y=39, z=3}, {name="default:water_source"})
		minetest.set_node({x=354, y=39, z=3}, {name="farming:soil_wet"})
		minetest.set_node({x=352, y=39, z=3}, {name="farming:soil_wet"})
		minetest.set_node({x=352, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=353, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=354, y=39, z=4}, {name="farming:soil_wet"})
		minetest.set_node({x=352, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=353, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=354, y=39, z=2}, {name="farming:soil_wet"})
		minetest.set_node({x=354, y=40, z=3}, {name="farming:cotton_8"})
		minetest.set_node({x=352, y=40, z=3}, {name="farming:cotton_8"})
		minetest.set_node({x=352, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=353, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=354, y=40, z=4}, {name="farming:cotton_8"})
		minetest.set_node({x=352, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=353, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=354, y=40, z=2}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=39, z=0}, {name="default:water_source"})
		minetest.set_node({x=351, y=39, z=0}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=0}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=1}, {name="farming:soil_wet"})
		minetest.set_node({x=350, y=39, z=1}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=39, z=1}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=-1}, {name="farming:soil_wet"})
		minetest.set_node({x=350, y=39, z=-1}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=39, z=-1}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=40, z=0}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=0}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=1}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=40, z=1}, {name="farming:cotton_8"})
		minetest.set_node({x=351, y=40, z=1}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=-1}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=40, z=-1}, {name="farming:cotton_8"})
		minetest.set_node({x=351, y=40, z=-1}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=39, z=6}, {name="default:water_source"})
		minetest.set_node({x=351, y=39, z=6}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=6}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=7}, {name="farming:soil_wet"})
		minetest.set_node({x=350, y=39, z=7}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=39, z=7}, {name="farming:soil_wet"})
		minetest.set_node({x=349, y=39, z=5}, {name="farming:soil_wet"})
		minetest.set_node({x=350, y=39, z=5}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=39, z=5}, {name="farming:soil_wet"})
		minetest.set_node({x=351, y=40, z=6}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=6}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=7}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=40, z=7}, {name="farming:cotton_8"})
		minetest.set_node({x=351, y=40, z=7}, {name="farming:cotton_8"})
		minetest.set_node({x=349, y=40, z=5}, {name="farming:cotton_8"})
		minetest.set_node({x=350, y=40, z=5}, {name="farming:cotton_8"})
		minetest.set_node({x=351, y=40, z=5}, {name="farming:cotton_8"})
    elseif v+0 == 0 then
        for j=346,354 do
            for i=0,7 do
                minetest.set_node({x=j, y=39, z=i}, {name="default:stone"})
            end
			minetest.set_node({x=j, y=39, z=-1}, {name="default:stone"})
        end
		for j=346,354 do
            for i=0,7 do
                minetest.set_node({x=j, y=40, z=i}, {name="air"})
            end
			minetest.set_node({x=j, y=40, z=-1}, {name="air"})
        end
        minetest.set_node({x=345, y=40, z=-2}, {name="air"})
    end
end