function Meadow(v,player)
    if v+0 == 1 then
        minetest.set_node({x=322, y=39, z=3}, {name="air"})
    elseif v+0 == 2 then
        minetest.set_node({x=321, y=39, z=3}, {name="air"})
		minetest.set_node({x=323, y=39, z=3}, {name="air"})
		minetest.set_node({x=322, y=39, z=4}, {name="air"})
		minetest.set_node({x=322, y=39, z=2}, {name="air"})
    elseif v+0 == 3 then
        minetest.set_node({x=320, y=39, z=3}, {name="air"})
		minetest.set_node({x=324, y=39, z=3}, {name="air"})
		minetest.set_node({x=322, y=39, z=5}, {name="air"})
		minetest.set_node({x=322, y=39, z=1}, {name="air"})
		minetest.set_node({x=323, y=39, z=2}, {name="air"})
		minetest.set_node({x=323, y=39, z=4}, {name="air"})
		minetest.set_node({x=321, y=39, z=2}, {name="air"})
		minetest.set_node({x=321, y=39, z=4}, {name="air"})
    elseif v+0 == 4 then
		minetest.set_node({x=322, y=39, z=3}, {name="default:desert_stone_block"})
		minetest.set_node({x=322, y=40, z=3}, {name="default:desert_stone_block"})
		minetest.set_node({x=322, y=41, z=3}, {name="default:water_source"})
    elseif v+0 == 5 then
        minetest.set_node({x=322, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=323, y=39, z=1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=2}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=3}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=4}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=323, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=322, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=321, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=4}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=3}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=2}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=321, y=39, z=1}, {name="castrum:dirt_with_grass"})
	elseif v+0 == 6 then
		minetest.set_node({x=322, y=39, z=-1}, {name="castrum:dirt_with_grass"})
        minetest.set_node({x=323, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=2}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=3}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=4}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=323, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=322, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=321, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=4}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=3}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=2}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=321, y=39, z=0}, {name="castrum:dirt_with_grass"})
	elseif v+0 == 7 then
        minetest.set_node({x=326, y=39, z=4}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=323, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=321, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=4}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=2}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=321, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=323, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=2}, {name="castrum:dirt_with_grass"})
	elseif v+0 == 8 then
		minetest.set_node({x=318, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=318, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=319, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=320, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=0}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=-1}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=5}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=326, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=6}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=325, y=39, z=7}, {name="castrum:dirt_with_grass"})
		minetest.set_node({x=324, y=39, z=7}, {name="castrum:dirt_with_grass"})
	elseif v+0 == 9 then
		minetest.set_node({x=326, y=40, z=2}, {name="flowers:dandelion_white"})
		minetest.set_node({x=324, y=40, z=0}, {name="flowers:dandelion_white"})
		minetest.set_node({x=322, y=40, z=-1}, {name="flowers:dandelion_white"})
		minetest.set_node({x=319, y=40, z=-1}, {name="flowers:dandelion_white"})
		minetest.set_node({x=318, y=40, z=3}, {name="flowers:dandelion_white"})
		minetest.set_node({x=320, y=40, z=5}, {name="flowers:dandelion_white"})
		minetest.set_node({x=321, y=40, z=7}, {name="flowers:dandelion_white"})
		minetest.set_node({x=324, y=40, z=6}, {name="flowers:dandelion_white"})
		minetest.set_node({x=326, y=40, z=5}, {name="flowers:dandelion_white"})
		minetest.set_node({x=326, y=40, z=3}, {name="flowers:rose"})
		minetest.set_node({x=325, y=40, z=0}, {name="flowers:rose"})
		minetest.set_node({x=322, y=40, z=0}, {name="flowers:rose"})
		minetest.set_node({x=319, y=40, z=1}, {name="flowers:rose"})
		minetest.set_node({x=319, y=40, z=4}, {name="flowers:rose"})
		minetest.set_node({x=318, y=40, z=6}, {name="flowers:rose"})
		minetest.set_node({x=322, y=40, z=6}, {name="flowers:rose"})
		minetest.set_node({x=324, y=40, z=5}, {name="flowers:rose"})
		minetest.set_node({x=326, y=40, z=7}, {name="flowers:rose"})
		minetest.set_node({x=327, y=40, z=8}, {name="default:chest"})
		screwdriver_handler(player, {type="node", under={x=327, y=40, z=8}, above={x=327, y=40, z=8}}, 1)
		screwdriver_handler(player, {type="node", under={x=327, y=40, z=8}, above={x=327, y=40, z=8}}, 1)
		screwdriver_handler(player, {type="node", under={x=327, y=40, z=8}, above={x=327, y=40, z=8}}, 1)
    elseif v+0 == 0 then
        for j=318,326 do
            for i=0,7 do
                minetest.set_node({x=j, y=39, z=i}, {name="default:stone"})
				minetest.set_node({x=j, y=40, z=i}, {name="air"})
				minetest.set_node({x=j, y=41, z=i}, {name="air"})
            end
			minetest.set_node({x=j, y=39, z=-1}, {name="default:stone"})
			minetest.set_node({x=j, y=40, z=-1}, {name="air"})
			minetest.set_node({x=j, y=41, z=-1}, {name="air"})
        end
		minetest.set_node({x=327, y=40, z=8}, {name="air"})
    end
end