function Mine(v,player)
    if v+0 == 1 then
        minetest.set_node({x=-16, y=9, z=-7}, {name="default:stone_with_coal"})
        minetest.set_node({x=-18, y=9, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-17, y=9, z=-13}, {name="default:stone_with_coal"})
        minetest.set_node({x=-14, y=9, z=-11}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=9, z=-8}, {name="default:stone_with_coal"})
        minetest.set_node({x=-11, y=9, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=9, z=-14}, {name="default:stone_with_coal"})
        minetest.set_node({x=-20, y=9, z=-15}, {name="default:chest"})
        screwdriver_handler(player, {type="node", under={x=-20, y=9, z=-15}, above={x=-20, y=9, z=-15}}, 1)
    elseif v+0 == 2 then
        minetest.set_node({x=-17, y=9, z=-7}, {name="default:stone_with_coal"})
        minetest.set_node({x=-16, y=9, z=-6}, {name="default:stone_with_coal"})
        minetest.set_node({x=-15, y=9, z=-7}, {name="default:stone_with_coal"})
        minetest.set_node({x=-16, y=9, z=-8}, {name="default:stone_with_coal"})
        minetest.set_node({x=-16, y=10, z=-7}, {name="default:stone_with_coal"})
        minetest.set_node({x=-19, y=9, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-18, y=9, z=-9}, {name="default:stone_with_coal"})
        minetest.set_node({x=-17, y=9, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-18, y=9, z=-11}, {name="default:stone_with_coal"})
        minetest.set_node({x=-18, y=10, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-18, y=9, z=-13}, {name="default:stone_with_coal"})
        minetest.set_node({x=-17, y=9, z=-12}, {name="default:stone_with_coal"})
        minetest.set_node({x=-16, y=9, z=-13}, {name="default:stone_with_coal"})
        minetest.set_node({x=-17, y=9, z=-14}, {name="default:stone_with_coal"})
        minetest.set_node({x=-17, y=10, z=-13}, {name="default:stone_with_coal"})
        minetest.set_node({x=-15, y=9, z=-11}, {name="default:stone_with_coal"})
        minetest.set_node({x=-14, y=9, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=9, z=-11}, {name="default:stone_with_coal"})
        minetest.set_node({x=-14, y=9, z=-12}, {name="default:stone_with_coal"})
        minetest.set_node({x=-14, y=10, z=-11}, {name="default:stone_with_coal"})
        minetest.set_node({x=-14, y=9, z=-8}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=9, z=-7}, {name="default:stone_with_coal"})
        minetest.set_node({x=-12, y=9, z=-8}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=9, z=-9}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=10, z=-8}, {name="default:stone_with_coal"})
        minetest.set_node({x=-12, y=9, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-11, y=9, z=-9}, {name="default:stone_with_coal"})
        minetest.set_node({x=-11, y=9, z=-11}, {name="default:stone_with_coal"})
        minetest.set_node({x=-11, y=10, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-14, y=9, z=-14}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=9, z=-13}, {name="default:stone_with_coal"})
        minetest.set_node({x=-12, y=9, z=-14}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=10, z=-14}, {name="default:stone_with_coal"})
    elseif v+0 == 3 then
        minetest.set_node({x=-16, y=11, z=-7}, {name="default:stone_with_coal"})
        minetest.set_node({x=-18, y=11, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-17, y=11, z=-13}, {name="default:stone_with_coal"})
        minetest.set_node({x=-14, y=11, z=-11}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=11, z=-8}, {name="default:stone_with_coal"})
        minetest.set_node({x=-11, y=11, z=-10}, {name="default:stone_with_coal"})
        minetest.set_node({x=-13, y=11, z=-14}, {name="default:stone_with_coal"})
        minetest.set_node({x=-19, y=9, z=-12}, {name="default:stone_with_iron"})
        minetest.set_node({x=-18, y=9, z=-8}, {name="default:stone_with_iron"})
        minetest.set_node({x=-15, y=9, z=-9}, {name="default:stone_with_iron"})
        minetest.set_node({x=-15, y=9, z=-13}, {name="default:stone_with_iron"})
        minetest.set_node({x=-14, y=9, z=-6}, {name="default:stone_with_iron"})
        minetest.set_node({x=-12, y=9, z=-12}, {name="default:stone_with_iron"})
        minetest.set_node({x=-11, y=9, z=-7}, {name="default:stone_with_iron"})
	elseif v+0 == 4 then
		minetest.set_node({x=-19, y=10, z=-12}, {name="default:stone_with_iron"})
        minetest.set_node({x=-18, y=10, z=-8}, {name="default:stone_with_iron"})
        minetest.set_node({x=-15, y=10, z=-9}, {name="default:stone_with_iron"})
        minetest.set_node({x=-15, y=10, z=-13}, {name="default:stone_with_iron"})
        minetest.set_node({x=-14, y=10, z=-6}, {name="default:stone_with_iron"})
        minetest.set_node({x=-12, y=10, z=-12}, {name="default:stone_with_iron"})
        minetest.set_node({x=-11, y=10, z=-7}, {name="default:stone_with_iron"})
		minetest.set_node({x=-12, y=9, z=-7}, {name="default:stone_with_iron"})
		minetest.set_node({x=-11, y=9, z=-6}, {name="default:stone_with_iron"})
		minetest.set_node({x=-11, y=9, z=-8}, {name="default:stone_with_iron"})
		minetest.set_node({x=-13, y=9, z=-6}, {name="default:stone_with_iron"})
		minetest.set_node({x=-14, y=9, z=-7}, {name="default:stone_with_iron"})
		minetest.set_node({x=-15, y=9, z=-6}, {name="default:stone_with_iron"})
		minetest.set_node({x=-14, y=9, z=-9}, {name="default:stone_with_iron"})
		minetest.set_node({x=-15, y=9, z=-10}, {name="default:stone_with_iron"})
		minetest.set_node({x=-15, y=9, z=-8}, {name="default:stone_with_iron"})
		minetest.set_node({x=-16, y=9, z=-9}, {name="default:stone_with_iron"})
		minetest.set_node({x=-11, y=9, z=-12}, {name="default:stone_with_iron"})
		minetest.set_node({x=-12, y=9, z=-13}, {name="default:stone_with_iron"})
		minetest.set_node({x=-12, y=9, z=-11}, {name="default:stone_with_iron"})
		minetest.set_node({x=-13, y=9, z=-12}, {name="default:stone_with_iron"})
		minetest.set_node({x=-14, y=9, z=-13}, {name="default:stone_with_iron"})
		minetest.set_node({x=-15, y=9, z=-12}, {name="default:stone_with_iron"})
		minetest.set_node({x=-15, y=9, z=-14}, {name="default:stone_with_iron"})
		minetest.set_node({x=-18, y=9, z=-7}, {name="default:stone_with_iron"})
		minetest.set_node({x=-17, y=9, z=-8}, {name="default:stone_with_iron"})
		minetest.set_node({x=-19, y=9, z=-8}, {name="default:stone_with_iron"})
		minetest.set_node({x=-19, y=9, z=-11}, {name="default:stone_with_iron"})
		minetest.set_node({x=-18, y=9, z=-12}, {name="default:stone_with_iron"})
		minetest.set_node({x=-19, y=9, z=-13}, {name="default:stone_with_iron"})
	elseif v+0 == 5 then
		minetest.set_node({x=-19, y=11, z=-12}, {name="default:stone_with_iron"})
        minetest.set_node({x=-18, y=11, z=-8}, {name="default:stone_with_iron"})
        minetest.set_node({x=-15, y=11, z=-9}, {name="default:stone_with_iron"})
        minetest.set_node({x=-15, y=11, z=-13}, {name="default:stone_with_iron"})
        minetest.set_node({x=-14, y=11, z=-6}, {name="default:stone_with_iron"})
        minetest.set_node({x=-12, y=11, z=-12}, {name="default:stone_with_iron"})
        minetest.set_node({x=-11, y=11, z=-7}, {name="default:stone_with_iron"})
		minetest.set_node({x=-12, y=9, z=-9}, {name="default:stone_with_tin"})
		minetest.set_node({x=-16, y=9, z=-11}, {name="default:stone_with_tin"})
		minetest.set_node({x=-12, y=9, z=-6}, {name="default:stone_with_copper"})
		minetest.set_node({x=-13, y=9, z=-10}, {name="default:stone_with_copper"})
		minetest.set_node({x=-11, y=9, z=-13}, {name="default:stone_with_copper"})
		minetest.set_node({x=-18, y=9, z=-6}, {name="default:stone_with_copper"})
		minetest.set_node({x=-18, y=9, z=-14}, {name="default:stone_with_copper"})
	elseif v+0 == 6 then
		minetest.set_node({x=-12, y=10, z=-9}, {name="default:stone_with_tin"})
		minetest.set_node({x=-16, y=10, z=-11}, {name="default:stone_with_tin"})
		minetest.set_node({x=-12, y=10, z=-6}, {name="default:stone_with_copper"})
		minetest.set_node({x=-13, y=10, z=-10}, {name="default:stone_with_copper"})
		minetest.set_node({x=-11, y=10, z=-13}, {name="default:stone_with_copper"})
		minetest.set_node({x=-18, y=10, z=-6}, {name="default:stone_with_copper"})
		minetest.set_node({x=-18, y=10, z=-14}, {name="default:stone_with_copper"})
		minetest.set_node({x=-11, y=9, z=-14}, {name="default:stone_with_copper"})
		minetest.set_node({x=-17, y=9, z=-6}, {name="default:stone_with_copper"})
		minetest.set_node({x=-19, y=9, z=-6}, {name="default:stone_with_copper"})
		minetest.set_node({x=-19, y=9, z=-14}, {name="default:stone_with_copper"})
		minetest.set_node({x=-16, y=9, z=-10}, {name="default:stone_with_tin"})
		minetest.set_node({x=-16, y=9, z=-12}, {name="default:stone_with_tin"})
		minetest.set_node({x=-17, y=9, z=-11}, {name="default:stone_with_tin"})
    elseif v+0 == 0 then 
        for j=11,19 do
            for i=6,14 do
                for k=9,14 do
                    minetest.set_node({x=j*(-1), y=k, z=i*(-1)}, {name="air"})
                end
            end
        end
        minetest.set_node({x=-20, y=9, z=-15}, {name="air"})
    end
end