function Mountain_Quarry(v,player)
    if v+0 == 1 then
        minetest.set_node({x=349, y=40, z=-9}, {name="default:mossycobble"})
		minetest.set_node({x=349, y=40, z=-7}, {name="default:mossycobble"})
		minetest.set_node({x=350, y=40, z=-8}, {name="default:mossycobble"})
		minetest.set_node({x=348, y=40, z=-8}, {name="default:mossycobble"})
		minetest.set_node({x=349, y=41, z=-8}, {name="default:mossycobble"})
		minetest.set_node({x=347, y=40, z=-12}, {name="default:mossycobble"})
		minetest.set_node({x=347, y=40, z=-10}, {name="default:mossycobble"})
		minetest.set_node({x=348, y=40, z=-11}, {name="default:mossycobble"})
		minetest.set_node({x=346, y=40, z=-11}, {name="default:mossycobble"})
		minetest.set_node({x=347, y=41, z=-11}, {name="default:mossycobble"})
		minetest.set_node({x=348, y=40, z=-15}, {name="default:mossycobble"})
		minetest.set_node({x=348, y=40, z=-13}, {name="default:mossycobble"})
		minetest.set_node({x=349, y=40, z=-14}, {name="default:mossycobble"})
		minetest.set_node({x=347, y=40, z=-14}, {name="default:mossycobble"})
		minetest.set_node({x=348, y=41, z=-14}, {name="default:mossycobble"})
		minetest.set_node({x=351, y=40, z=-11}, {name="default:mossycobble"})
		minetest.set_node({x=351, y=40, z=-13}, {name="default:mossycobble"})
		minetest.set_node({x=350, y=40, z=-12}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=40, z=-12}, {name="default:mossycobble"})
		minetest.set_node({x=351, y=41, z=-12}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=40, z=-10}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=40, z=-8}, {name="default:mossycobble"})
		minetest.set_node({x=351, y=40, z=-9}, {name="default:mossycobble"})
		minetest.set_node({x=353, y=40, z=-9}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=41, z=-9}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=40, z=-14}, {name="default:mossycobble"})
		minetest.set_node({x=351, y=40, z=-15}, {name="default:mossycobble"})
		minetest.set_node({x=353, y=40, z=-15}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=41, z=-15}, {name="default:mossycobble"})
		minetest.set_node({x=354, y=40, z=-12}, {name="default:mossycobble"})
		minetest.set_node({x=354, y=40, z=-10}, {name="default:mossycobble"})
		minetest.set_node({x=353, y=40, z=-11}, {name="default:mossycobble"})
		minetest.set_node({x=354, y=41, z=-11}, {name="default:mossycobble"})
	elseif v+0 == 2 then
		minetest.set_node({x=349, y=42, z=-8}, {name="default:mossycobble"})
		minetest.set_node({x=347, y=42, z=-11}, {name="default:mossycobble"})
		minetest.set_node({x=348, y=42, z=-14}, {name="default:mossycobble"})
		minetest.set_node({x=351, y=42, z=-12}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=42, z=-9}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=42, z=-15}, {name="default:mossycobble"})
		minetest.set_node({x=354, y=42, z=-11}, {name="default:mossycobble"})
    elseif v+0 == 0 then
        for i=346,354 do
            for k=40,43 do
                for j=7,15 do
                    minetest.set_node({x=i, y=k, z=j*(-1)}, {name="air"})
                end
            end
        end
		minetest.set_node({x=349, y=40, z=-8}, {name="default:mossycobble"})
		minetest.set_node({x=347, y=40, z=-11}, {name="default:mossycobble"})
		minetest.set_node({x=348, y=40, z=-14}, {name="default:mossycobble"})
		minetest.set_node({x=351, y=40, z=-12}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=40, z=-9}, {name="default:mossycobble"})
		minetest.set_node({x=352, y=40, z=-15}, {name="default:mossycobble"})
		minetest.set_node({x=354, y=40, z=-11}, {name="default:mossycobble"})
    end
end