function Quarry(v,player)
    if v+0 == 1 then
        minetest.set_node({x=-17, y=9, z=6}, {name="default:stone"})
        minetest.set_node({x=-16, y=9, z=7}, {name="default:stone"})
        minetest.set_node({x=-15, y=9, z=6}, {name="default:stone"})
        minetest.set_node({x=-16, y=9, z=5}, {name="default:stone"})
        minetest.set_node({x=-16, y=10, z=6}, {name="default:stone"})
        minetest.set_node({x=-19, y=9, z=3}, {name="default:stone"})
        minetest.set_node({x=-18, y=9, z=4}, {name="default:stone"})
        minetest.set_node({x=-17, y=9, z=3}, {name="default:stone"})
        minetest.set_node({x=-18, y=9, z=2}, {name="default:stone"})
        minetest.set_node({x=-18, y=10, z=3}, {name="default:stone"})
        minetest.set_node({x=-18, y=9, z=0}, {name="default:stone"})
        minetest.set_node({x=-17, y=9, z=1}, {name="default:stone"})
        minetest.set_node({x=-16, y=9, z=0}, {name="default:stone"})
        minetest.set_node({x=-17, y=9, z=-1}, {name="default:stone"})
        minetest.set_node({x=-17, y=10, z=0}, {name="default:stone"})
        minetest.set_node({x=-15, y=9, z=2}, {name="default:stone"})
        minetest.set_node({x=-14, y=9, z=3}, {name="default:stone"})
        minetest.set_node({x=-13, y=9, z=2}, {name="default:stone"})
        minetest.set_node({x=-14, y=9, z=1}, {name="default:stone"})
        minetest.set_node({x=-14, y=10, z=2}, {name="default:stone"})
        minetest.set_node({x=-14, y=9, z=5}, {name="default:stone"})
        minetest.set_node({x=-13, y=9, z=6}, {name="default:stone"})
        minetest.set_node({x=-12, y=9, z=5}, {name="default:stone"})
        minetest.set_node({x=-13, y=9, z=4}, {name="default:stone"})
        minetest.set_node({x=-13, y=10, z=5}, {name="default:stone"})
        minetest.set_node({x=-12, y=9, z=3}, {name="default:stone"})
        minetest.set_node({x=-11, y=9, z=4}, {name="default:stone"})
        minetest.set_node({x=-11, y=9, z=2}, {name="default:stone"})
        minetest.set_node({x=-11, y=10, z=3}, {name="default:stone"})
        minetest.set_node({x=-14, y=9, z=-1}, {name="default:stone"})
        minetest.set_node({x=-13, y=9, z=0}, {name="default:stone"})
        minetest.set_node({x=-12, y=9, z=-1}, {name="default:stone"})
        minetest.set_node({x=-13, y=10, z=-1}, {name="default:stone"})
    elseif v+0 == 2 then
        minetest.set_node({x=-16, y=11, z=6}, {name="default:stone"})
        minetest.set_node({x=-18, y=11, z=3}, {name="default:stone"})
        minetest.set_node({x=-17, y=11, z=0}, {name="default:stone"})
        minetest.set_node({x=-14, y=11, z=2}, {name="default:stone"})
        minetest.set_node({x=-13, y=11, z=5}, {name="default:stone"})
        minetest.set_node({x=-11, y=11, z=3}, {name="default:stone"})
        minetest.set_node({x=-13, y=11, z=-1}, {name="default:stone"})
        minetest.set_node({x=-19, y=9, z=1}, {name="default:desert_stone"})
        minetest.set_node({x=-18, y=9, z=5}, {name="default:desert_stone"})
        minetest.set_node({x=-15, y=9, z=4}, {name="default:desert_stone"})
        minetest.set_node({x=-15, y=9, z=0}, {name="default:desert_stone"})
        minetest.set_node({x=-14, y=9, z=7}, {name="default:desert_stone"})
        minetest.set_node({x=-12, y=9, z=1}, {name="default:desert_stone"})
        minetest.set_node({x=-11, y=9, z=6}, {name="default:desert_stone"})
	elseif v+0 == 3 then
        minetest.set_node({x=-19, y=10, z=1}, {name="default:desert_stone"})
        minetest.set_node({x=-18, y=10, z=5}, {name="default:desert_stone"})
        minetest.set_node({x=-15, y=10, z=4}, {name="default:desert_stone"})
        minetest.set_node({x=-15, y=10, z=0}, {name="default:desert_stone"})
        minetest.set_node({x=-14, y=10, z=7}, {name="default:desert_stone"})
        minetest.set_node({x=-12, y=10, z=1}, {name="default:desert_stone"})
        minetest.set_node({x=-11, y=10, z=6}, {name="default:desert_stone"})
		minetest.set_node({x=-11, y=9, z=7}, {name="default:desert_stone"})
		minetest.set_node({x=-11, y=9, z=5}, {name="default:desert_stone"})
		minetest.set_node({x=-12, y=9, z=6}, {name="default:desert_stone"})
		minetest.set_node({x=-13, y=9, z=7}, {name="default:desert_stone"})
		minetest.set_node({x=-15, y=9, z=7}, {name="default:desert_stone"})
		minetest.set_node({x=-14, y=9, z=6}, {name="default:desert_stone"})
		minetest.set_node({x=-13, y=9, z=1}, {name="default:desert_stone"})
		minetest.set_node({x=-11, y=9, z=1}, {name="default:desert_stone"})
		minetest.set_node({x=-12, y=9, z=2}, {name="default:desert_stone"})
		minetest.set_node({x=-12, y=9, z=0}, {name="default:desert_stone"})
		minetest.set_node({x=-14, y=9, z=4}, {name="default:desert_stone"})
		minetest.set_node({x=-16, y=9, z=4}, {name="default:desert_stone"})
		minetest.set_node({x=-15, y=9, z=3}, {name="default:desert_stone"})
		minetest.set_node({x=-15, y=9, z=5}, {name="default:desert_stone"})
		minetest.set_node({x=-14, y=9, z=0}, {name="default:desert_stone"})
		minetest.set_node({x=-15, y=9, z=1}, {name="default:desert_stone"})
		minetest.set_node({x=-15, y=9, z=-1}, {name="default:desert_stone"})
		minetest.set_node({x=-17, y=9, z=5}, {name="default:desert_stone"})
		minetest.set_node({x=-19, y=9, z=5}, {name="default:desert_stone"})
		minetest.set_node({x=-18, y=9, z=6}, {name="default:desert_stone"})
		minetest.set_node({x=-18, y=9, z=1}, {name="default:desert_stone"})
		minetest.set_node({x=-19, y=9, z=2}, {name="default:desert_stone"})
		minetest.set_node({x=-19, y=9, z=0}, {name="default:desert_stone"})
	elseif v+0 == 4 then
		minetest.set_node({x=-19, y=11, z=1}, {name="default:desert_stone"})
        minetest.set_node({x=-18, y=11, z=5}, {name="default:desert_stone"})
        minetest.set_node({x=-15, y=11, z=4}, {name="default:desert_stone"})
        minetest.set_node({x=-15, y=11, z=0}, {name="default:desert_stone"})
        minetest.set_node({x=-14, y=11, z=7}, {name="default:desert_stone"})
        minetest.set_node({x=-12, y=11, z=1}, {name="default:desert_stone"})
        minetest.set_node({x=-11, y=11, z=6}, {name="default:desert_stone"})
		minetest.set_node({x=-12, y=9, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-12, y=9, z=4}, {name="default:obsidian"})
		minetest.set_node({x=-11, y=9, z=0}, {name="default:obsidian"})
		minetest.set_node({x=-13, y=9, z=3}, {name="default:obsidian"})
		minetest.set_node({x=-16, y=9, z=2}, {name="default:obsidian"})
		minetest.set_node({x=-18, y=9, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-18, y=9, z=-1}, {name="default:obsidian"})
	elseif v+0 == 5 then
		minetest.set_node({x=-12, y=10, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-12, y=10, z=4}, {name="default:obsidian"})
		minetest.set_node({x=-11, y=10, z=0}, {name="default:obsidian"})
		minetest.set_node({x=-13, y=10, z=3}, {name="default:obsidian"})
		minetest.set_node({x=-16, y=10, z=2}, {name="default:obsidian"})
		minetest.set_node({x=-18, y=10, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-18, y=10, z=-1}, {name="default:obsidian"})
		minetest.set_node({x=-11, y=9, z=-1}, {name="default:obsidian"})
		minetest.set_node({x=-16, y=9, z=3}, {name="default:obsidian"})
		minetest.set_node({x=-16, y=9, z=1}, {name="default:obsidian"})
		minetest.set_node({x=-17, y=9, z=2}, {name="default:obsidian"})
		minetest.set_node({x=-17, y=9, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-19, y=9, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-19, y=9, z=-1}, {name="default:obsidian"})
	elseif v+0 == 6 then
		minetest.set_node({x=-12, y=11, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-12, y=11, z=4}, {name="default:obsidian"})
		minetest.set_node({x=-11, y=11, z=0}, {name="default:obsidian"})
		minetest.set_node({x=-13, y=11, z=3}, {name="default:obsidian"})
		minetest.set_node({x=-16, y=11, z=2}, {name="default:obsidian"})
		minetest.set_node({x=-18, y=11, z=7}, {name="default:obsidian"})
		minetest.set_node({x=-18, y=11, z=-1}, {name="default:obsidian"})
    elseif v+0 == 0 then
        for j=11,19 do
            for i=0,7 do
                for k=9,14 do
                    minetest.set_node({x=j*(-1), y=k, z=i}, {name="air"})
                end
            end
        end
        for j=11,19 do
            for k=9,14 do
                minetest.set_node({x=j*(-1), y=k, z=-1}, {name="air"})
            end
        end
        minetest.set_node({x=-16, y=9, z=6}, {name="default:stone"})
        minetest.set_node({x=-18, y=9, z=3}, {name="default:stone"})
        minetest.set_node({x=-17, y=9, z=0}, {name="default:stone"})
        minetest.set_node({x=-14, y=9, z=2}, {name="default:stone"})
        minetest.set_node({x=-13, y=9, z=5}, {name="default:stone"})
        minetest.set_node({x=-11, y=9, z=3}, {name="default:stone"})
        minetest.set_node({x=-13, y=9, z=-1}, {name="default:stone"})
    end
end