function Sandmine(v,player)
    if v+0 == 1 then
        minetest.set_node({x=129, y=9, z=10}, {name="default:sandstone"})
        minetest.set_node({x=131, y=9, z=10}, {name="default:sandstone"})
        minetest.set_node({x=130, y=9, z=9}, {name="default:sandstone"})
        minetest.set_node({x=130, y=9, z=11}, {name="default:sandstone"})
        minetest.set_node({x=130, y=10, z=10}, {name="default:sandstone"})
        minetest.set_node({x=127, y=9, z=7}, {name="default:sandstone"})
        minetest.set_node({x=129, y=9, z=7}, {name="default:sandstone"})
        minetest.set_node({x=128, y=9, z=6}, {name="default:sandstone"})
        minetest.set_node({x=128, y=9, z=8}, {name="default:sandstone"})
        minetest.set_node({x=128, y=10, z=7}, {name="default:sandstone"})
        minetest.set_node({x=128, y=9, z=13}, {name="default:sandstone"})
        minetest.set_node({x=130, y=9, z=13}, {name="default:sandstone"})
        minetest.set_node({x=129, y=9, z=12}, {name="default:sandstone"})
        minetest.set_node({x=129, y=9, z=14}, {name="default:sandstone"})
        minetest.set_node({x=129, y=10, z=13}, {name="default:sandstone"})
        minetest.set_node({x=125, y=9, z=11}, {name="default:sandstone"})
        minetest.set_node({x=127, y=9, z=11}, {name="default:sandstone"})
        minetest.set_node({x=126, y=9, z=10}, {name="default:sandstone"})
        minetest.set_node({x=126, y=9, z=12}, {name="default:sandstone"})
        minetest.set_node({x=126, y=10, z=11}, {name="default:sandstone"})
        minetest.set_node({x=124, y=9, z=8}, {name="default:sandstone"})
        minetest.set_node({x=126, y=9, z=8}, {name="default:sandstone"})
        minetest.set_node({x=125, y=9, z=7}, {name="default:sandstone"})
        minetest.set_node({x=125, y=9, z=9}, {name="default:sandstone"})
        minetest.set_node({x=125, y=10, z=8}, {name="default:sandstone"})
        minetest.set_node({x=124, y=9, z=14}, {name="default:sandstone"})
        minetest.set_node({x=125, y=9, z=13}, {name="default:sandstone"})
        minetest.set_node({x=126, y=9, z=14}, {name="default:sandstone"})
        minetest.set_node({x=125, y=10, z=14}, {name="default:sandstone"})
        minetest.set_node({x=123, y=9, z=9}, {name="default:sandstone"})
        minetest.set_node({x=123, y=9, z=11}, {name="default:sandstone"})
        minetest.set_node({x=124, y=9, z=10}, {name="default:sandstone"})
        minetest.set_node({x=123, y=10, z=10}, {name="default:sandstone"})
    elseif v+0 == 2 then
        minetest.set_node({x=130, y=11, z=10}, {name="default:sandstone"})
        minetest.set_node({x=128, y=11, z=7}, {name="default:sandstone"})
        minetest.set_node({x=129, y=11, z=13}, {name="default:sandstone"})
        minetest.set_node({x=126, y=11, z=11}, {name="default:sandstone"})
        minetest.set_node({x=125, y=11, z=8}, {name="default:sandstone"})
        minetest.set_node({x=125, y=11, z=14}, {name="default:sandstone"})
        minetest.set_node({x=123, y=11, z=10}, {name="default:sandstone"})
        minetest.set_node({x=131, y=9, z=12}, {name="default:desert_sandstone"})
        minetest.set_node({x=130, y=9, z=8}, {name="default:desert_sandstone"})
        minetest.set_node({x=127, y=9, z=9}, {name="default:desert_sandstone"})
        minetest.set_node({x=127, y=9, z=13}, {name="default:desert_sandstone"})
        minetest.set_node({x=126, y=9, z=6}, {name="default:desert_sandstone"})
        minetest.set_node({x=124, y=9, z=12}, {name="default:desert_sandstone"})
        minetest.set_node({x=123, y=9, z=7}, {name="default:desert_sandstone"})
	elseif v+0 == 3 then
        minetest.set_node({x=131, y=10, z=12}, {name="default:desert_sandstone"})
        minetest.set_node({x=130, y=10, z=8}, {name="default:desert_sandstone"})
        minetest.set_node({x=127, y=10, z=9}, {name="default:desert_sandstone"})
        minetest.set_node({x=127, y=10, z=13}, {name="default:desert_sandstone"})
        minetest.set_node({x=126, y=10, z=6}, {name="default:desert_sandstone"})
        minetest.set_node({x=124, y=10, z=12}, {name="default:desert_sandstone"})
        minetest.set_node({x=123, y=10, z=7}, {name="default:desert_sandstone"}) 
		minetest.set_node({x=123, y=9, z=6}, {name="default:desert_sandstone"})
		minetest.set_node({x=123, y=9, z=8}, {name="default:desert_sandstone"})
		minetest.set_node({x=124, y=9, z=7}, {name="default:desert_sandstone"})
		minetest.set_node({x=124, y=9, z=11}, {name="default:desert_sandstone"})
		minetest.set_node({x=124, y=9, z=13}, {name="default:desert_sandstone"})
		minetest.set_node({x=123, y=9, z=12}, {name="default:desert_sandstone"})
		minetest.set_node({x=125, y=9, z=12}, {name="default:desert_sandstone"})
		minetest.set_node({x=126, y=9, z=7}, {name="default:desert_sandstone"})
		minetest.set_node({x=127, y=9, z=6}, {name="default:desert_sandstone"})
		minetest.set_node({x=125, y=9, z=6}, {name="default:desert_sandstone"})
		minetest.set_node({x=127, y=9, z=8}, {name="default:desert_sandstone"})
		minetest.set_node({x=127, y=9, z=10}, {name="default:desert_sandstone"})
		minetest.set_node({x=126, y=9, z=9}, {name="default:desert_sandstone"})
		minetest.set_node({x=128, y=9, z=9}, {name="default:desert_sandstone"})
		minetest.set_node({x=126, y=9, z=13}, {name="default:desert_sandstone"})
		minetest.set_node({x=127, y=9, z=14}, {name="default:desert_sandstone"})
		minetest.set_node({x=127, y=9, z=12}, {name="default:desert_sandstone"})
		minetest.set_node({x=130, y=9, z=7}, {name="default:desert_sandstone"})
		minetest.set_node({x=131, y=9, z=8}, {name="default:desert_sandstone"})
		minetest.set_node({x=129, y=9, z=8}, {name="default:desert_sandstone"})
		minetest.set_node({x=130, y=9, z=12}, {name="default:desert_sandstone"})
		minetest.set_node({x=131, y=9, z=13}, {name="default:desert_sandstone"})
		minetest.set_node({x=131, y=9, z=11}, {name="default:desert_sandstone"})
	elseif v+0 == 4 then
		minetest.set_node({x=131, y=11, z=12}, {name="default:desert_sandstone"})
        minetest.set_node({x=130, y=11, z=8}, {name="default:desert_sandstone"})
        minetest.set_node({x=127, y=11, z=9}, {name="default:desert_sandstone"})
        minetest.set_node({x=127, y=11, z=13}, {name="default:desert_sandstone"})
        minetest.set_node({x=126, y=11, z=6}, {name="default:desert_sandstone"})
        minetest.set_node({x=124, y=11, z=12}, {name="default:desert_sandstone"})
        minetest.set_node({x=123, y=11, z=7}, {name="default:desert_sandstone"})
		
		minetest.set_node({x=123, y=9, z=13}, {name="default:silver_sandstone"}) 
		minetest.set_node({x=123, y=9, z=13}, {name="default:silver_sandstone"})
		minetest.set_node({x=124, y=9, z=6}, {name="default:silver_sandstone"})
		minetest.set_node({x=124, y=9, z=9}, {name="default:silver_sandstone"})
		minetest.set_node({x=125, y=9, z=10}, {name="default:silver_sandstone"})
		minetest.set_node({x=128, y=9, z=11}, {name="default:silver_sandstone"})
		minetest.set_node({x=130, y=9, z=6}, {name="default:silver_sandstone"})
		minetest.set_node({x=130, y=9, z=14}, {name="default:silver_sandstone"})
    elseif v+0 == 0 then
        for j=123,131 do
            for i=6,14 do
                for k=9,14 do
                    minetest.set_node({x=j, y=k, z=i}, {name="air"})
                end
            end
        end
        minetest.set_node({x=130, y=9, z=10}, {name="default:sandstone"})
        minetest.set_node({x=128, y=9, z=7}, {name="default:sandstone"})
        minetest.set_node({x=129, y=9, z=13}, {name="default:sandstone"})
        minetest.set_node({x=126, y=9, z=11}, {name="default:sandstone"})
        minetest.set_node({x=125, y=9, z=8}, {name="default:sandstone"})
        minetest.set_node({x=125, y=9, z=14}, {name="default:sandstone"})
        minetest.set_node({x=123, y=9, z=10}, {name="default:sandstone"})
    end
end