function Tree(v,player)
    if v+0 == 1 then
        minetest.set_node({x=-15, y=9, z=16}, {name="default:tree"})
        minetest.set_node({x=-15, y=10, z=16}, {name="default:leaves"})
        minetest.set_node({x=-14, y=9, z=16}, {name="default:leaves"})
        minetest.set_node({x=-16, y=9, z=16}, {name="default:leaves"})
        minetest.set_node({x=-15, y=9, z=15}, {name="default:leaves"})
        minetest.set_node({x=-15, y=9, z=17}, {name="default:leaves"})
        minetest.set_node({x=-20, y=9, z=11}, {name="default:chest"})
        screwdriver_handler(player, {type="node", under={x=-20, y=9, z=11}, above={x=-20, y=9, z=11}}, 1)
    elseif v+0 == 2 then
        minetest.set_node({x=-15, y=10, z=16}, {name="default:tree"})
        minetest.set_node({x=-15, y=11, z=16}, {name="default:tree"})
        minetest.set_node({x=-15, y=12, z=16}, {name="default:leaves"})
        minetest.set_node({x=-14, y=11, z=16}, {name="default:leaves"})
        minetest.set_node({x=-16, y=11, z=16}, {name="default:leaves"})
        minetest.set_node({x=-15, y=11, z=17}, {name="default:leaves"})
        minetest.set_node({x=-15, y=11, z=15}, {name="default:leaves"})
        minetest.set_node({x=-14, y=11, z=15}, {name="default:leaves"})
        minetest.set_node({x=-14, y=11, z=17}, {name="default:leaves"})
        minetest.set_node({x=-16, y=11, z=15}, {name="default:leaves"})
        minetest.set_node({x=-16, y=11, z=17}, {name="default:leaves"})
        minetest.set_node({x=-14, y=9, z=16}, {name="air"})
        minetest.set_node({x=-16, y=9, z=16}, {name="air"})
        minetest.set_node({x=-15, y=9, z=15}, {name="air"})
        minetest.set_node({x=-15, y=9, z=17}, {name="air"})
    elseif v+0 == 3 then
        minetest.set_node({x=-15, y=12, z=16}, {name="default:tree"})
        minetest.set_node({x=-14, y=11, z=16}, {name="air"})
        minetest.set_node({x=-16, y=11, z=16}, {name="air"})
        minetest.set_node({x=-15, y=11, z=17}, {name="air"})
        minetest.set_node({x=-15, y=11, z=15}, {name="air"})
        minetest.set_node({x=-14, y=11, z=15}, {name="air"})
        minetest.set_node({x=-14, y=11, z=17}, {name="air"})
        minetest.set_node({x=-16, y=11, z=15}, {name="air"})
        minetest.set_node({x=-16, y=11, z=17}, {name="air"})
        minetest.set_node({x=-14, y=12, z=16}, {name="default:leaves"})
        minetest.set_node({x=-16, y=12, z=16}, {name="default:leaves"})
        minetest.set_node({x=-15, y=12, z=17}, {name="default:leaves"})
        minetest.set_node({x=-15, y=12, z=15}, {name="default:leaves"})
        minetest.set_node({x=-14, y=12, z=15}, {name="default:leaves"})
        minetest.set_node({x=-14, y=12, z=17}, {name="default:leaves"})
        minetest.set_node({x=-16, y=12, z=15}, {name="default:leaves"})
        minetest.set_node({x=-16, y=12, z=17}, {name="default:leaves"})
        minetest.set_node({x=-17, y=12, z=16}, {name="default:leaves"})
        minetest.set_node({x=-13, y=12, z=16}, {name="default:leaves"})
        minetest.set_node({x=-15, y=12, z=14}, {name="default:leaves"})
        minetest.set_node({x=-15, y=12, z=18}, {name="default:leaves"})
        minetest.set_node({x=-15, y=13, z=16}, {name="default:leaves"})
        minetest.set_node({x=-14, y=13, z=16}, {name="default:leaves"})
        minetest.set_node({x=-16, y=13, z=16}, {name="default:leaves"})
        minetest.set_node({x=-15, y=13, z=17}, {name="default:leaves"})
        minetest.set_node({x=-15, y=13, z=15}, {name="default:leaves"})
        minetest.set_node({x=-12, y=9, z=19}, {name="default:jungletree"})
        minetest.set_node({x=-12, y=10, z=19}, {name="default:jungleleaves"})
        minetest.set_node({x=-11, y=9, z=19}, {name="default:jungleleaves"})
        minetest.set_node({x=-13, y=9, z=19}, {name="default:jungleleaves"})
        minetest.set_node({x=-12, y=9, z=18}, {name="default:jungleleaves"})
        minetest.set_node({x=-12, y=9, z=20}, {name="default:jungleleaves"})
	elseif v+0 == 4 then
        minetest.set_node({x=-12, y=10, z=19}, {name="default:jungletree"})
		minetest.set_node({x=-12, y=11, z=19}, {name="default:jungletree"})
		minetest.set_node({x=-11, y=11, z=18}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=11, z=18}, {name="default:jungleleaves"})
		minetest.set_node({x=-13, y=11, z=18}, {name="default:jungleleaves"})
		minetest.set_node({x=-11, y=11, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=11, z=19}, {name="default:jungletree"})
		minetest.set_node({x=-13, y=11, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-11, y=11, z=20}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=11, z=20}, {name="default:jungleleaves"})
		minetest.set_node({x=-13, y=11, z=20}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=12, z=19}, {name="default:jungleleaves"})
        minetest.set_node({x=-11, y=9, z=19}, {name="air"})
        minetest.set_node({x=-13, y=9, z=19}, {name="air"})
        minetest.set_node({x=-12, y=9, z=18}, {name="air"})
        minetest.set_node({x=-12, y=9, z=20}, {name="air"})
	elseif v+0 == 5 then
		minetest.set_node({x=-12, y=12, z=19}, {name="default:jungletree"})
		minetest.set_node({x=-11, y=11, z=18}, {name="air"})
		minetest.set_node({x=-12, y=11, z=18}, {name="air"})
		minetest.set_node({x=-13, y=11, z=18}, {name="air"})
		minetest.set_node({x=-11, y=11, z=19}, {name="air"})
		minetest.set_node({x=-13, y=11, z=19}, {name="air"})
		minetest.set_node({x=-11, y=11, z=20}, {name="air"})
		minetest.set_node({x=-12, y=11, z=20}, {name="air"})
		minetest.set_node({x=-13, y=11, z=20}, {name="air"})
		minetest.set_node({x=-11, y=12, z=18}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=12, z=18}, {name="default:jungleleaves"})
		minetest.set_node({x=-13, y=12, z=18}, {name="default:jungleleaves"})
		minetest.set_node({x=-11, y=12, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-13, y=12, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-11, y=12, z=20}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=12, z=20}, {name="default:jungleleaves"})
		minetest.set_node({x=-13, y=12, z=20}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=13, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-14, y=12, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=12, z=17}, {name="default:jungleleaves"})
		minetest.set_node({x=-13, y=13, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=13, z=18}, {name="default:jungleleaves"})
		minetest.set_node({x=-11, y=13, z=19}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=13, z=20}, {name="default:jungleleaves"})
		minetest.set_node({x=-12, y=9, z=13}, {name="default:pine_tree"})
		minetest.set_node({x=-12, y=9, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=9, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=9, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-13, y=9, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=10, z=13}, {name="default:pine_needles"})
	elseif v+0 == 6 then
		minetest.set_node({x=-12, y=10, z=13}, {name="default:pine_tree"})
		minetest.set_node({x=-12, y=11, z=13}, {name="default:pine_tree"})
		
		minetest.set_node({x=-13, y=11, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=11, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=11, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-13, y=11, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=11, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=11, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=11, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-13, y=11, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=12, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=9, z=14}, {name="air"})
		minetest.set_node({x=-12, y=9, z=12}, {name="air"})
		minetest.set_node({x=-11, y=9, z=13}, {name="air"})
		minetest.set_node({x=-13, y=9, z=13}, {name="air"})
	elseif v+0 == 7 then
		minetest.set_node({x=-12, y=12, z=13}, {name="default:pine_tree"})
		minetest.set_node({x=-12, y=11, z=14}, {name="air"})
		minetest.set_node({x=-12, y=11, z=12}, {name="air"})
		minetest.set_node({x=-11, y=11, z=14}, {name="air"})
		minetest.set_node({x=-11, y=11, z=13}, {name="air"})
		minetest.set_node({x=-11, y=11, z=12}, {name="air"})
		minetest.set_node({x=-13, y=11, z=14}, {name="air"})
		minetest.set_node({x=-13, y=11, z=13}, {name="air"})
		minetest.set_node({x=-13, y=11, z=12}, {name="air"})
		minetest.set_node({x=-13, y=12, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=12, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=12, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-13, y=12, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=12, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=12, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=12, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-13, y=12, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=13, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-11, y=13, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-13, y=13, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=13, z=12}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=13, z=14}, {name="default:pine_needles"})
		minetest.set_node({x=-12, y=12, z=15}, {name="default:pine_needles"})
		minetest.set_node({x=-14, y=12, z=13}, {name="default:pine_needles"})
		minetest.set_node({x=-18, y=9, z=19}, {name="default:acacia_tree"})
		minetest.set_node({x=-18, y=9, z=20}, {name="default:acacia_leaves"})
		minetest.set_node({x=-18, y=9, z=18}, {name="default:acacia_leaves"})
		minetest.set_node({x=-17, y=9, z=19}, {name="default:acacia_leaves"})
		minetest.set_node({x=-19, y=9, z=19}, {name="default:acacia_leaves"})
		minetest.set_node({x=-18, y=10, z=19}, {name="default:acacia_leaves"})
    elseif v+0 == 0 then
        for j=11,19 do
            for i=12,20 do
                for k=9,14 do
                    minetest.set_node({x=j*(-1), y=k, z=i}, {name="air"})
                end
            end
        end
        minetest.set_node({x=-20, y=9, z=11}, {name="air"})
    end
end